title: RNAfold.AI
description: Illuminating the dark genome with AI
taglong: Illuminating the dark genome with AI
tagshort: ""
url: https://rnafold.ai
baseurl: ""
permalink: pretty
repo: https://github.com/

# author settings

author:
  name: RNAfold.AI
  email: hallo@rnafold.ai
photo: /assets/jpg/photo.jpg

#  facebook: username
#  github: username
#  instagram: username
#  linkedin: username
#  stackoverflow: 0000000/username
#  twitter: username

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
